import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased max-w-7xl mx-auto relative`}
      >
       
          <header className="bg-neutral-800 fixed p-2 w-full max-w-7xl   flex items-center justify-between">
            <p>MM</p>
            <p>Linkedin</p>
            </header>
       
        {children}
      </body>
    </html>
  );
}
